### ISSUE TITLE
Semantic DOM Feedback! 

### ISSUE THREAD

**Issue by rijkvanzanten** [Bhakti-Garach/manuscript#1]
- [Watch your indentation](https://github.com/Bhakti-Garach/manuscript/blob/b72d38370945dcadcfc7ea7d20d780145dc8a47e/index.html#L9). It feels like a silly thing at first, but it really helps making sense of HTML once the pages grow in size
- Thing of headings—eg `h1`, `h2`, `h3` as chapters titles of a book. With that in mind, is a [book's author a chapter sub-sub-title](https://github.com/Bhakti-Garach/manuscript/blob/b72d38370945dcadcfc7ea7d20d780145dc8a47e/index.html#L11)?
- Similarly, each `h2` starts a new "chapter". Therefore you're effectively [starting 3 chapters back to back with the repeated `h2`s](https://github.com/Bhakti-Garach/manuscript/blob/b72d38370945dcadcfc7ea7d20d780145dc8a47e/index.html#L12-L14)
- Right now your response is semantically [just another 'sub-chapter' of the article itself](https://github.com/Bhakti-Garach/manuscript/blob/b72d38370945dcadcfc7ea7d20d780145dc8a47e/index.html#L50). Consider wrapping it separately in an [`<article>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article) to indicate that it's a standalone piece of content on the page
- [You're jumping from the `h3` section straight into an `h5`](https://github.com/Bhakti-Garach/manuscript/blob/b72d38370945dcadcfc7ea7d20d780145dc8a47e/index.html#L60), skipping the `h4` you'd expect in between

**Comment by Bhakti-Garach** [comment]
Hi Rijk! Thanks for the feddback. All updates done!
