### ISSUE TITLE
Styled Markup Feedback!

### ISSUE THREAD

**Issue by mfehrenbach** [Bhakti-Garach/manuscript#2]
- [x] Solid indentation game, to start.

- [x] I don’t think this is [a list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul)? 

    https://github.com/Bhakti-Garach/manuscript/blob/32d4920c4ed29c0b0abc2876422b476d129a2644/index.html#L18-L28

- [x] I would “flip” the hierarchy, throughout. `[article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article) > [section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)`.

    https://github.com/Bhakti-Garach/manuscript/blob/32d4920c4ed29c0b0abc2876422b476d129a2644/index.html#L30-L38

- [x] Ah, a [description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)! Rare but perfect for these:

    https://github.com/Bhakti-Garach/manuscript/blob/32d4920c4ed29c0b0abc2876422b476d129a2644/index.html#L92-L96

- [x] Would like to see some more inline semantic consideration (beyond the occasional `em`). Probably some `cite`, some `q`, some links out? (Also the `span` is maybe a `mark`?)

- [x] Moving into design proper—I like the vibe here (very “crisp”) but it is also _veeery_ even. What can we do to bring some hierarchy/visually expressive moments down the page? It is a bit of a “wall of text” and I need some “handholds”. (This is exacerbated by the monospaced type sameness, so you’ll need to go harder against it.) 

- [x] Recent trick for center-aligned: [`text-wrap: balance;`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap)

    <img width="1059" alt="image" src="https://github.com/user-attachments/assets/4509ef9b-73ac-4d39-8937-116d71c2f212">

    <img width="678" alt="image" src="https://github.com/user-attachments/assets/daa91caf-c806-4207-a9c2-a07fc814ead6">

- [x] Not enough difference/distance between these headings and body, nor between the body and the `em`. I’d get those more distinct:

    <img width="628" alt="image" src="https://github.com/user-attachments/assets/4a266526-60c9-4975-8697-dbd3da8ab50b">

- [x] On base readability, the lines are maybe 25% too long and are asking for some more vertical space between paragraphs.

- [x] I almost gasped down here! Where has this hard yellow been the whole time? I would introduce it earlier so it feels like an overall motif.

    <img width="1326" alt="image" src="https://github.com/user-attachments/assets/c4afdb59-7ff3-421d-bca1-5778592ca826">

Overall, good code fundamentals and now we want to see a focus on pushing the visual design. Turn up that “volume”! Invite us into the text, visually, so it doesn’t feel quite as impenetrable. Situate us as we go through it. Lean into your flourishes, and bring them throughout!

✊

**Comment by Bhakti-Garach** [comment]
Thanks Michael! Updated as per feedback
